server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.99:3306/hwldb?useUnicode=true&characterEncoding=UTF-8
    username: zekun
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  type-aliases-package: com.huowulian365.domain
  mapper-locations: com/huowulian365/mapper/*.xml